// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAor7KMHdcbRwJxBY-6xeVM5PAdjxESoDk',
    appId: '1:513543158869:web:d246a45986a8a0dc98a8dc',
    messagingSenderId: '513543158869',
    projectId: 'my-app-67e63',
    authDomain: 'my-app-67e63.firebaseapp.com',
    storageBucket: 'my-app-67e63.firebasestorage.app',
    measurementId: 'G-DX8EBTE397',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuRhdH9ujMyek6YZc6YtyJ-3Ms9dYUrcI',
    appId: '1:513543158869:android:0330380a6620814898a8dc',
    messagingSenderId: '513543158869',
    projectId: 'my-app-67e63',
    storageBucket: 'my-app-67e63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWpj00bF5oqgH6mp2V1ooV8Baz3WBOqI8',
    appId: '1:513543158869:ios:e615b323ca4cfd7898a8dc',
    messagingSenderId: '513543158869',
    projectId: 'my-app-67e63',
    storageBucket: 'my-app-67e63.firebasestorage.app',
    iosBundleId: 'com.example.atividadeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWpj00bF5oqgH6mp2V1ooV8Baz3WBOqI8',
    appId: '1:513543158869:ios:e615b323ca4cfd7898a8dc',
    messagingSenderId: '513543158869',
    projectId: 'my-app-67e63',
    storageBucket: 'my-app-67e63.firebasestorage.app',
    iosBundleId: 'com.example.atividadeFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAor7KMHdcbRwJxBY-6xeVM5PAdjxESoDk',
    appId: '1:513543158869:web:6cd8683df8708eee98a8dc',
    messagingSenderId: '513543158869',
    projectId: 'my-app-67e63',
    authDomain: 'my-app-67e63.firebaseapp.com',
    storageBucket: 'my-app-67e63.firebasestorage.app',
    measurementId: 'G-V5VTQTPCPB',
  );
}
